[tool.poetry]
name = "levinson-durbin"
version = "0.1.0"
description = ""
authors = ["sdual <shr.nrht.0623@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "1.17.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
